CREATE TABLE [USERS] (
[USER_ID]   INTEGER         DEFAULT 100 NOT NULL PRIMARY KEY AUTOINCREMENT,
[PHONE]     VARCHAR(20)     DEFAULT '+7'            UNIQUE  NOT NULL,
[NICKNAME]  VARCHAR(20)     DEFAULT NULL            UNIQUE  NULL,
[FULLNAME]  NVARCHAR(255)   DEFAULT ''                      NULL,
[DATEREG]   TIMESTAMP       DEFAULT CURRENT_TIMESTAMP       NOT NULL
)
;;
CREATE TABLE [DEVICES] (
[USER_ID]   INTEGER         DEFAULT -1                      NOT NULL,
[DEVICE_ID] VARCHAR(250)    DEFAULT 0                       NOT NULL,
[DEVICE_NAME] VARCHAR(100)  DEFAULT ''                      NOT NULL,
[ACTIVE]    INTEGER         DEFAULT 0                       NOT NULL,
[DELETED]   INTEGER         DEFAULT 0                       NOT NULL,
[SMS_CODE]  VARCHAR(10)     DEFAULT ''                      NOT NULL,
[DATE_BIND] TIMESTAMP       DEFAULT CURRENT_TIMESTAMP       NOT NULL,
[ATTEMPTS]  INTEGER         DEFAULT 5                       NOT NULL
)
;;
CREATE TABLE [BOOK] (
[USER_ID]       INTEGER         DEFAULT -1          NOT NULL,
[FRIEND_PHONE]  VARCHAR(20)     DEFAULT '+7'        NOT NULL,
[FRIEND_ID]     INTEGER         DEFAULT NULL        NULL,
[FULLNAME]  NVARCHAR(255)   DEFAULT NULL            NULL
)
;
