SELECT
    D.USER_ID
    , D.DEVICE_ID
    , D.DEVICE_NAME
    , D.ACTIVE
    , D.DELETED
    , D.ATTEMPTS
FROM DEVICES D
JOIN USERS U
    USING(USER_ID)
WHERE  U.PHONE = '@PHONE@'
    AND DEVICE_ID = '@DEVICE_ID@'
;