UPDATE DEVICES
SET
    ACTIVE = CASE WHEN SMS_CODE = '@SMS_CODE@' AND ATTEMPTS >0 THEN 1 ELSE 0 END
    , DELETED = CASE WHEN ATTEMPTS <= 0 THEN 1 ELSE 0 END
    , ATTEMPTS = ATTEMPTS - 1
WHERE USER_ID = @USER_ID@
    AND DEVICE_ID = '@DEVICE_ID@'
    AND DELETED =0
;